"""Hardening checklists extracted from the provided documents.

Each checklist item has:
- id: unique identifier
- category: grouping (e.g., "SSH", "Firewall", "Password Policy")
- description: human-readable check description
- check_command: shell command to run on the target (via SSH)
- expected: expected output/condition (regex or exact match)
- os: "linux" or "windows"
- severity: critical, high, medium, low
- remediation: command or steps to fix if check fails
"""

LINUX_CHECKLIST = [
    {
        "id": "L-PHYS-01",
        "category": "Physical System Security",
        "description": "GRUB bootloader should be password-protected",
        "check_command": "grep -i '^password' /boot/grub2/grub.cfg 2>/dev/null || grep -i '^set superusers' /boot/grub2/grub.cfg 2>/dev/null || echo 'NOT_FOUND'",
        "expected": r"(password|set superusers)",
        "os": "linux",
        "severity": "medium",
        "remediation": "grub2-setpassword",
    },
    {
        "id": "L-DISK-01",
        "category": "Disk Partitions",
        "description": "/tmp should be on a separate partition with noexec,nosuid,nodev",
        "check_command": "mount | grep ' /tmp ' || echo 'NOT_FOUND'",
        "expected": r"on /tmp",
        "os": "linux",
        "severity": "medium",
        "remediation": "Create separate /tmp partition with noexec,nosuid,nodev options",
    },
    {
        "id": "L-DISK-02",
        "category": "Disk Partitions",
        "description": "/home should be on a separate partition",
        "check_command": "mount | grep ' /home ' || echo 'NOT_FOUND'",
        "expected": r"on /home",
        "os": "linux",
        "severity": "medium",
        "remediation": "Create separate /home partition",
    },
    {
        "id": "L-DISK-03",
        "category": "Disk Partitions",
        "description": "/var should be on a separate partition",
        "check_command": "mount | grep ' /var ' || echo 'NOT_FOUND'",
        "expected": r"on /var",
        "os": "linux",
        "severity": "medium",
        "remediation": "Create separate /var partition",
    },
    {
        "id": "L-PKG-01",
        "category": "Package Management",
        "description": "No Telnet server installed",
        "check_command": "rpm -q telnet-server 2>/dev/null || dpkg -l telnetd 2>/dev/null || echo 'NOT_INSTALLED'",
        "expected": r"(not installed|NOT_INSTALLED|no packages)",
        "os": "linux",
        "severity": "high",
        "remediation": "yum remove telnet-server || apt-get remove telnetd",
    },
    {
        "id": "L-PKG-02",
        "category": "Package Management",
        "description": "No rsh server installed",
        "check_command": "rpm -q rsh-server 2>/dev/null || dpkg -l rsh-server 2>/dev/null || echo 'NOT_INSTALLED'",
        "expected": r"(not installed|NOT_INSTALLED|no packages)",
        "os": "linux",
        "severity": "high",
        "remediation": "yum remove rsh-server || apt-get remove rsh-server",
    },
    {
        "id": "L-PKG-03",
        "category": "Package Management",
        "description": "X Window System not installed on servers",
        "check_command": "rpm -q xorg-x11-server-Xorg 2>/dev/null || dpkg -l xserver-xorg 2>/dev/null || echo 'NOT_INSTALLED'",
        "expected": r"(not installed|NOT_INSTALLED|no packages|NOT_FOUND)",
        "os": "linux",
        "severity": "medium",
        "remediation": "yum remove xorg-x11-server-Xorg || apt-get remove xserver-xorg",
    },
    {
        "id": "L-SSH-01",
        "category": "SSH Hardening",
        "description": "SSH PermitRootLogin should be disabled",
        "check_command": "grep -i '^PermitRootLogin' /etc/ssh/sshd_config || echo 'DEFAULT'",
        "expected": r"PermitRootLogin\s+(no|without-password|prohibit-password)",
        "os": "linux",
        "severity": "critical",
        "remediation": "sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config && systemctl restart sshd",
    },
    {
        "id": "L-SSH-02",
        "category": "SSH Hardening",
        "description": "SSH Protocol should be version 2 only",
        "check_command": "grep -i '^Protocol' /etc/ssh/sshd_config || echo 'DEFAULT'",
        "expected": r"(Protocol 2|DEFAULT)",
        "os": "linux",
        "severity": "high",
        "remediation": "sed -i 's/^Protocol.*/Protocol 2/' /etc/ssh/sshd_config && systemctl restart sshd",
    },
    {
        "id": "L-SSH-03",
        "category": "SSH Hardening",
        "description": "SSH MaxAuthTries should be set to 3 or less",
        "check_command": "grep -i '^MaxAuthTries' /etc/ssh/sshd_config || echo 'DEFAULT'",
        "expected": r"MaxAuthTries\s+[0-3]$",
        "os": "linux",
        "severity": "medium",
        "remediation": "sed -i 's/^MaxAuthTries.*/MaxAuthTries 3/' /etc/ssh/sshd_config && systemctl restart sshd",
    },
    {
        "id": "L-SSH-04",
        "category": "SSH Hardening",
        "description": "SSH empty passwords should be disabled",
        "check_command": "grep -i '^PermitEmptyPasswords' /etc/ssh/sshd_config || echo 'DEFAULT'",
        "expected": r"(PermitEmptyPasswords no|DEFAULT)",
        "os": "linux",
        "severity": "critical",
        "remediation": "sed -i 's/^PermitEmptyPasswords.*/PermitEmptyPasswords no/' /etc/ssh/sshd_config && systemctl restart sshd",
    },
    {
        "id": "L-SSH-05",
        "category": "SSH Hardening",
        "description": "SSH X11Forwarding should be disabled",
        "check_command": "grep -i '^X11Forwarding' /etc/ssh/sshd_config || echo 'DEFAULT'",
        "expected": r"(X11Forwarding no|DEFAULT)",
        "os": "linux",
        "severity": "medium",
        "remediation": "sed -i 's/^X11Forwarding.*/X11Forwarding no/' /etc/ssh/sshd_config && systemctl restart sshd",
    },
    {
        "id": "L-SSH-06",
        "category": "SSH Hardening",
        "description": "SSH ClientAliveInterval should be set (300s or less)",
        "check_command": "grep -i '^ClientAliveInterval' /etc/ssh/sshd_config || echo 'NOT_SET'",
        "expected": r"ClientAliveInterval\s+([0-9]|[1-9][0-9]|[1-2][0-9][0-9]|300)$",
        "os": "linux",
        "severity": "low",
        "remediation": "sed -i 's/^ClientAliveInterval.*/ClientAliveInterval 300/' /etc/ssh/sshd_config && systemctl restart sshd",
    },
    {
        "id": "L-SSH-07",
        "category": "SSH Hardening",
        "description": "SSH LoginGraceTime should be 60 or less",
        "check_command": "grep -i '^LoginGraceTime' /etc/ssh/sshd_config || echo 'DEFAULT'",
        "expected": r"LoginGraceTime\s+([0-9]|[1-5][0-9]|60)$",
        "os": "linux",
        "severity": "medium",
        "remediation": "sed -i 's/^LoginGraceTime.*/LoginGraceTime 60/' /etc/ssh/sshd_config && systemctl restart sshd",
    },
    {
        "id": "L-FW-01",
        "category": "Firewall",
        "description": "iptables firewall should be active with default DROP policy",
        "check_command": "iptables -L INPUT -n 2>/dev/null | head -1 || echo 'NOT_AVAILABLE'",
        "expected": r"Chain INPUT.*policy DROP",
        "os": "linux",
        "severity": "high",
        "remediation": "iptables -P INPUT DROP && iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT && iptables -A INPUT -i lo -j ACCEPT && iptables-save > /etc/sysconfig/iptables",
    },
    {
        "id": "L-FW-02",
        "category": "Firewall",
        "description": "firewalld should be active",
        "check_command": "systemctl is-active firewalld 2>/dev/null || echo 'INACTIVE'",
        "expected": r"active",
        "os": "linux",
        "severity": "high",
        "remediation": "systemctl enable --now firewalld",
    },
    {
        "id": "L-PORTS-01",
        "category": "Network Services",
        "description": "No unnecessary listening ports (only SSH, DNS, HTTP/S expected)",
        "check_command": "ss -tlnp 2>/dev/null | grep -v ':22\\b' | grep -v ':53\\b' | grep -v ':80\\b' | grep -v ':443\\b' | grep -v '127.0.0.1' | grep LISTEN || echo 'CLEAN'",
        "expected": r"(CLEAN|^$)",
        "os": "linux",
        "severity": "medium",
        "remediation": "Disable unnecessary services: systemctl disable --now <service>",
    },
    {
        "id": "L-SVC-01",
        "category": "Services",
        "description": "Avahi/mDNS should be disabled",
        "check_command": "systemctl is-active avahi-daemon 2>/dev/null || echo 'INACTIVE'",
        "expected": r"(inactive|not-found|INACTIVE)",
        "os": "linux",
        "severity": "medium",
        "remediation": "systemctl disable --now avahi-daemon",
    },
    {
        "id": "L-SVC-02",
        "category": "Services",
        "description": "CUPS printing should be disabled on servers",
        "check_command": "systemctl is-active cups 2>/dev/null || echo 'INACTIVE'",
        "expected": r"(inactive|not-found|INACTIVE)",
        "os": "linux",
        "severity": "low",
        "remediation": "systemctl disable --now cups",
    },
    {
        "id": "L-SVC-03",
        "category": "Services",
        "description": "NFS server should be disabled if not needed",
        "check_command": "systemctl is-active nfs-server 2>/dev/null || echo 'INACTIVE'",
        "expected": r"(inactive|not-found|INACTIVE)",
        "os": "linux",
        "severity": "medium",
        "remediation": "systemctl disable --now nfs-server",
    },
    {
        "id": "L-AUTH-01",
        "category": "Authentication",
        "description": "Password aging: max days should be 90 or less",
        "check_command": "grep -E '^PASS_MAX_DAYS' /etc/login.defs || echo 'DEFAULT'",
        "expected": r"PASS_MAX_DAYS\s+([0-9]|[1-8][0-9]|90)$",
        "os": "linux",
        "severity": "medium",
        "remediation": "sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS 90/' /etc/login.defs",
    },
    {
        "id": "L-AUTH-02",
        "category": "Authentication",
        "description": "Password minimum length should be 14 or more",
        "check_command": "grep -E '^PASS_MIN_LEN' /etc/login.defs || echo 'DEFAULT'",
        "expected": r"PASS_MIN_LEN\s+(1[4-9]|[2-9][0-9]|[1-9][0-9]{2,})",
        "os": "linux",
        "severity": "medium",
        "remediation": "sed -i 's/^PASS_MIN_LEN.*/PASS_MIN_LEN 14/' /etc/login.defs",
    },
    {
        "id": "L-AUTH-03",
        "category": "Authentication",
        "description": "Password history should be remembered (min 5)",
        "check_command": "grep -i 'pam_unix.so' /etc/pam.d/system-auth 2>/dev/null | grep -i 'remember' || echo 'NOT_SET'",
        "expected": r"remember=[5-9]|[1-9][0-9]",
        "os": "linux",
        "severity": "medium",
        "remediation": "Add 'remember=5' to pam_unix.so in /etc/pam.d/system-auth",
    },
    {
        "id": "L-AUTH-04",
        "category": "Authentication",
        "description": "Root should only be accessible via sudo",
        "check_command": "grep -E '^root' /etc/passwd | cut -d: -f7 || echo 'UNKNOWN'",
        "expected": r"(/bin/bash|/bin/sh)",
        "os": "linux",
        "severity": "low",
        "remediation": "Use sudo instead of direct root login",
    },
    {
        "id": "L-AUTH-05",
        "category": "Authentication",
        "description": "Empty password accounts should not exist",
        "check_command": "awk -F: '($2 == \"\") {print $1}' /etc/shadow 2>/dev/null || echo 'NO_EMPTY'",
        "expected": r"(NO_EMPTY|^$)",
        "os": "linux",
        "severity": "critical",
        "remediation": "passwd -l <username> for accounts with empty passwords",
    },
    {
        "id": "L-KERN-01",
        "category": "Kernel Security",
        "description": "IP forwarding should be disabled",
        "check_command": "sysctl net.ipv4.ip_forward 2>/dev/null || echo 'NOT_SET'",
        "expected": r"net.ipv4.ip_forward\s*=\s*0",
        "os": "linux",
        "severity": "medium",
        "remediation": "sysctl -w net.ipv4.ip_forward=0 && echo 'net.ipv4.ip_forward=0' >> /etc/sysctl.conf",
    },
    {
        "id": "L-KERN-02",
        "category": "Kernel Security",
        "description": "ICMP redirect should be disabled",
        "check_command": "sysctl net.ipv4.conf.all.accept_redirects 2>/dev/null || echo 'NOT_SET'",
        "expected": r"net.ipv4.conf.all.accept_redirects\s*=\s*0",
        "os": "linux",
        "severity": "medium",
        "remediation": "sysctl -w net.ipv4.conf.all.accept_redirects=0",
    },
    {
        "id": "L-KERN-03",
        "category": "Kernel Security",
        "description": "Source routed packets should be rejected",
        "check_command": "sysctl net.ipv4.conf.all.accept_source_route 2>/dev/null || echo 'NOT_SET'",
        "expected": r"net.ipv4.conf.all.accept_source_route\s*=\s*0",
        "os": "linux",
        "severity": "medium",
        "remediation": "sysctl -w net.ipv4.conf.all.accept_source_route=0",
    },
    {
        "id": "L-KERN-04",
        "category": "Kernel Security",
        "description": "SYN flood protection should be enabled",
        "check_command": "sysctl net.ipv4.tcp_syncookies 2>/dev/null || echo 'NOT_SET'",
        "expected": r"net.ipv4.tcp_syncookies\s*=\s*1",
        "os": "linux",
        "severity": "medium",
        "remediation": "sysctl -w net.ipv4.tcp_syncookies=1",
    },
    {
        "id": "L-LOG-01",
        "category": "Logging",
        "description": "rsyslog or syslog-ng should be running",
        "check_command": "systemctl is-active rsyslog 2>/dev/null || systemctl is-active syslog-ng 2>/dev/null || echo 'INACTIVE'",
        "expected": r"active",
        "os": "linux",
        "severity": "high",
        "remediation": "systemctl enable --now rsyslog",
    },
    {
        "id": "L-LOG-02",
        "category": "Logging",
        "description": "Audit daemon should be running",
        "check_command": "systemctl is-active auditd 2>/dev/null || echo 'INACTIVE'",
        "expected": r"active",
        "os": "linux",
        "severity": "medium",
        "remediation": "systemctl enable --now auditd",
    },
    {
        "id": "L-PERM-01",
        "category": "File Permissions",
        "description": "/etc/passwd should be 644",
        "check_command": "stat -c '%a' /etc/passwd",
        "expected": r"^644$",
        "os": "linux",
        "severity": "medium",
        "remediation": "chmod 644 /etc/passwd",
    },
    {
        "id": "L-PERM-02",
        "category": "File Permissions",
        "description": "/etc/shadow should be 600",
        "check_command": "stat -c '%a' /etc/shadow 2>/dev/null || echo 'NOT_FOUND'",
        "expected": r"^600$",
        "os": "linux",
        "severity": "high",
        "remediation": "chmod 600 /etc/shadow",
    },
    {
        "id": "L-PERM-03",
        "category": "File Permissions",
        "description": "/etc/ssh/sshd_config should be 600",
        "check_command": "stat -c '%a' /etc/ssh/sshd_config",
        "expected": r"^600$",
        "os": "linux",
        "severity": "medium",
        "remediation": "chmod 600 /etc/ssh/sshd_config",
    },
    {
        "id": "L-UPD-01",
        "category": "Updates",
        "description": "System should have recent security updates (last update within 30 days)",
        "check_command": "rpm -qa --last 2>/dev/null | head -1 || ls -lt /var/log/apt/history.log 2>/dev/null | tail -1 || echo 'UNKNOWN'",
        "expected": r"(202[5-6]|202[0-9])",
        "os": "linux",
        "severity": "high",
        "remediation": "yum update --security || apt-get upgrade -y",
    },
]

WINDOWS_CHECKLIST = [
    {
        "id": "W-PATCH-01",
        "category": "OS and Patch Management",
        "description": "Latest cumulative update installed",
        "check_command": 'powershell -Command "Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 1 | ForEach-Object { $_.InstalledOn.ToString(\'yyyy-MM-dd\') }"',
        "expected": None,
        "os": "windows",
        "severity": "high",
        "remediation": "Install latest Windows cumulative update via WSUS or Windows Update",
    },
    {
        "id": "W-PATCH-02",
        "category": "OS and Patch Management",
        "description": "Windows Update service should be running",
        "check_command": 'powershell -Command "Get-Service wuauserv | Select-Object -ExpandProperty Status"',
        "expected": r"Running",
        "os": "windows",
        "severity": "high",
        "remediation": "Set-Service wuauserv -StartupType Automatic; Start-Service wuauserv",
    },
    {
        "id": "W-PATCH-03",
        "category": "OS and Patch Management",
        "description": "Windows Defender/EDR should be active",
        "check_command": 'powershell -Command "Get-MpComputerStatus | Select-Object -ExpandProperty RealTimeProtectionEnabled"',
        "expected": r"True",
        "os": "windows",
        "severity": "high",
        "remediation": "Set-MpPreference -DisableRealTimeMonitoring $false",
    },
    {
        "id": "W-PASS-01",
        "category": "Password Policy",
        "description": "Minimum password length should be 14 characters",
        "check_command": 'net accounts | findstr /C:"Minimum password length"',
        "expected": r"(1[4-9]|[2-9][0-9]|[1-9][0-9]{2,})",
        "os": "windows",
        "severity": "high",
        "remediation": "net accounts /minpwlen:14",
    },
    {
        "id": "W-PASS-02",
        "category": "Password Policy",
        "description": "Password history should be 24",
        "check_command": 'net accounts | findstr /C:"length of password history"',
        "expected": r"(2[4-9]|[3-9][0-9])",
        "os": "windows",
        "severity": "medium",
        "remediation": "net accounts /uniquepw:24",
    },
    {
        "id": "W-PASS-03",
        "category": "Password Policy",
        "description": "Maximum password age should be 60-90 days",
        "check_command": 'net accounts | findstr /C:"Maximum password age"',
        "expected": r"([6-9][0-9]|90)",
        "os": "windows",
        "severity": "medium",
        "remediation": "net accounts /maxpwage:90",
    },
    {
        "id": "W-PASS-04",
        "category": "Password Policy",
        "description": "Password complexity should be enabled",
        "check_command": 'net accounts | findstr /C:"Password meets complexity"',
        "expected": r"Yes",
        "os": "windows",
        "severity": "high",
        "remediation": "Configure password complexity via Group Policy or secpol.msc",
    },
    {
        "id": "W-LOCK-01",
        "category": "Account Lockout",
        "description": "Account lockout threshold should be 5 attempts",
        "check_command": 'net accounts | findstr /C:"lockout threshold"',
        "expected": r"5",
        "os": "windows",
        "severity": "medium",
        "remediation": "net accounts /lockoutthreshold:5",
    },
    {
        "id": "W-LOCK-02",
        "category": "Account Lockout",
        "description": "Account lockout duration should be 15 minutes",
        "check_command": 'net accounts | findstr /C:"lockout duration"',
        "expected": r"15",
        "os": "windows",
        "severity": "medium",
        "remediation": "net accounts /lockoutduration:15",
    },
    {
        "id": "W-ACCT-01",
        "category": "Built-in Accounts",
        "description": "Guest account should be disabled",
        "check_command": 'net user guest | findstr /C:"Account active"',
        "expected": r"No",
        "os": "windows",
        "severity": "high",
        "remediation": "net user guest /active:no",
    },
    {
        "id": "W-ACCT-02",
        "category": "Built-in Accounts",
        "description": "Administrator account should be renamed",
        "check_command": 'wmic useraccount where name="Administrator" get FullName /value 2>nul || echo "UNKNOWN"',
        "expected": r"(FullName=(?!Administrator)|UNKNOWN)",
        "os": "windows",
        "severity": "medium",
        "remediation": "wmic useraccount where name=\"Administrator\" rename NewAdminName",
    },
    {
        "id": "W-FW-01",
        "category": "Windows Firewall",
        "description": "Domain Firewall should be ON",
        "check_command": 'netsh advfirewall show domainprofile state',
        "expected": r"State\s+ON",
        "os": "windows",
        "severity": "high",
        "remediation": "netsh advfirewall set domainprofile state on",
    },
    {
        "id": "W-FW-02",
        "category": "Windows Firewall",
        "description": "Private Firewall should be ON",
        "check_command": 'netsh advfirewall show privateprofile state',
        "expected": r"State\s+ON",
        "os": "windows",
        "severity": "high",
        "remediation": "netsh advfirewall set privateprofile state on",
    },
    {
        "id": "W-FW-03",
        "category": "Windows Firewall",
        "description": "Public Firewall should be ON",
        "check_command": 'netsh advfirewall show publicprofile state',
        "expected": r"State\s+ON",
        "os": "windows",
        "severity": "high",
        "remediation": "netsh advfirewall set publicprofile state on",
    },
    {
        "id": "W-FW-04",
        "category": "Windows Firewall",
        "description": "Domain Firewall inbound default should be Block",
        "check_command": 'netsh advfirewall show domainprofile firewallpolicy',
        "expected": r"Inbound.*Block|BlockInbound",
        "os": "windows",
        "severity": "high",
        "remediation": "netsh advfirewall set domainprofile firewallpolicy blockinbound",
    },
    {
        "id": "W-SMB-01",
        "category": "SMB Security",
        "description": "SMBv1 should be disabled",
        "check_command": 'powershell -Command "Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol | Select-Object -ExpandProperty State"',
        "expected": r"Disabled",
        "os": "windows",
        "severity": "high",
        "remediation": "Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -NoRestart",
    },
    {
        "id": "W-SMB-02",
        "category": "SMB Security",
        "description": "SMB Server Signing should be enabled",
        "check_command": 'reg query "HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanmanServer\\Parameters" /v RequireSecuritySignature 2>nul | findstr /i "0x1"',
        "expected": r"0x1",
        "os": "windows",
        "severity": "high",
        "remediation": 'reg add "HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanmanServer\\Parameters" /v RequireSecuritySignature /t REG_DWORD /d 1 /f',
    },
    {
        "id": "W-SMB-03",
        "category": "SMB Security",
        "description": "LLMNR should be disabled",
        "check_command": 'reg query "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient" /v EnableMulticast 2>nul | findstr /i "0x0"',
        "expected": r"0x0",
        "os": "windows",
        "severity": "medium",
        "remediation": 'reg add "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient" /v EnableMulticast /t REG_DWORD /d 0 /f',
    },
    {
        "id": "W-AUTH-01",
        "category": "Authentication",
        "description": "LAN Manager auth level should be NTLMv2 only",
        "check_command": 'reg query "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa" /v LmCompatibilityLevel 2>nul | findstr /i "0x[3-5]"',
        "expected": r"0x[3-5]",
        "os": "windows",
        "severity": "high",
        "remediation": 'reg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa" /v LmCompatibilityLevel /t REG_DWORD /d 5 /f',
    },
    {
        "id": "W-AUTH-02",
        "category": "Authentication",
        "description": "Local accounts should not have admin privileges (count non-default admins)",
        "check_command": 'net localgroup Administrators 2>nul | findstr /v "Administrator" | findstr /v "---"',
        "expected": None,
        "os": "windows",
        "severity": "medium",
        "remediation": "Review and remove unnecessary local admin accounts",
    },
    {
        "id": "W-TIME-01",
        "category": "Time Synchronization",
        "description": "Windows Time service should be running",
        "check_command": 'powershell -Command "Get-Service w32time | Select-Object -ExpandProperty Status"',
        "expected": r"Running",
        "os": "windows",
        "severity": "medium",
        "remediation": "net start w32time && w32tm /resync",
    },
    {
        "id": "W-LOG-01",
        "category": "Audit Policy",
        "description": "Audit logon events should be enabled",
        "check_command": 'auditpol /get /subcategory:"Logon" 2>nul | findstr /i "Success and Failure"',
        "expected": r"Success and Failure",
        "os": "windows",
        "severity": "medium",
        "remediation": 'auditpol /set /subcategory:"Logon" /success:enable /failure:enable',
    },
    {
        "id": "W-LOG-02",
        "category": "Audit Policy",
        "description": "Audit account management should be enabled",
        "check_command": 'auditpol /get /subcategory:"User Account Management" 2>nul | findstr /i "Success"',
        "expected": r"Success",
        "os": "windows",
        "severity": "medium",
        "remediation": 'auditpol /set /subcategory:"User Account Management" /success:enable',
    },
    {
        "id": "W-SVC-01",
        "category": "Services",
        "description": "Remote Desktop should be disabled or restricted",
        "check_command": 'reg query "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server" /v fDenyTSConnections 2>nul | findstr /i "0x1"',
        "expected": r"0x1",
        "os": "windows",
        "severity": "medium",
        "remediation": 'reg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 1 /f',
    },
    {
        "id": "W-SVC-02",
        "category": "Services",
        "description": "WinRM should be disabled if not needed",
        "check_command": 'powershell -Command "Get-Service WinRM | Select-Object -ExpandProperty Status"',
        "expected": r"(Stopped|Unknown)",
        "os": "windows",
        "severity": "medium",
        "remediation": "Stop-Service WinRM; Set-Service WinRM -StartupType Disabled",
    },
    {
        "id": "W-UPDATE-01",
        "category": "Updates",
        "description": "Windows Update should be configured (not paused)",
        "check_command": 'reg query "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU" /v NoAutoUpdate 2>nul | findstr /i "0x1"',
        "expected": r"(NOT_FOUND|0x0)",
        "os": "windows",
        "severity": "high",
        "remediation": "Remove NoAutoUpdate registry key or set to 0",
    },
]


FORTIGATE_CHECKLIST = [
    # ─── WAN / Perimeter ──────────────────────────────────────────────
    {
        "id": "FG-WAN-01",
        "category": "WAN Interface Security",
        "description": "ICMP (ping) responses must be blocked on WAN interfaces via local-in policy",
        "check_command": "show firewall local-in-policy",
        "expected": r'(?s)(?=.*set\s+action\s+deny)(?=.*service\s+"?ALL_ICMP"?)',
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config firewall local-in-policy\n    edit 1\n        set intf \"wan1\"\n        set srcaddr all\n        set dstaddr all\n        set action deny\n        set service ALL_ICMP\n        set schedule always\n    next\nend",
        "reference": "FortiOS 6.4 Hardening Guide; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-WAN-02",
        "category": "WAN Interface Security",
        "description": "BGP responses must be blocked on WAN interfaces via local-in policy",
        "check_command": "show firewall local-in-policy",
        "expected": r'(?s)(?=.*set\s+action\s+deny)(?=.*service\s+"?BGP"?)',
        "os": "fortigate",
        "severity": "high",
        "remediation": "config firewall local-in-policy\n    edit 1\n        set intf \"wan1\"\n        set srcaddr all\n        set dstaddr all\n        set action deny\n        set service BGP\n        set schedule always\n    next\nend",
        "reference": "FortiOS 6.4 Hardening Guide; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-POL-01",
        "category": "Firewall Policy",
        "description": "All firewall policies must log traffic (no policy with logging disabled)",
        "check_command": "show firewall policy",
        "expected": r"(?s)^(?!.*set\s+logtraffic\s+disable)",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config firewall policy\n    edit <id>\n        set logtraffic all\n    next\nend",
        "reference": "NIST 800-53v5 AU-2/AU-6; SANS Firewall Auditing Checklist",
    },
    # ─── System Global ────────────────────────────────────────────────
    {
        "id": "FG-SYS-01",
        "category": "Telemetry",
        "description": "Anonymous statistics submission of known internal vulnerabilities to FortiGuard must be disabled (fis-status)",
        "check_command": "show system global",
        "expected": r"(?s)^(?!.*fis-status\s+enable)",
        "os": "fortigate",
        "severity": "low",
        "remediation": "config system global\n    set fis-status disable\nend",
        "reference": "FortiOS 6.4 Hardening Guide",
    },
    {
        "id": "FG-SYS-02",
        "category": "Telemetry",
        "description": "Anonymous Security Rating result submission to FortiGuard must be disabled",
        "check_command": "show system global",
        "expected": r"(?s)^(?!.*security-rating-result-submission\s+enable)",
        "os": "fortigate",
        "severity": "low",
        "remediation": "config system global\n    set security-rating-result-submission disable\nend",
        "reference": "FortiOS 6.4 Hardening Guide",
    },
    {
        "id": "FG-SYS-03",
        "category": "System Global",
        "description": "OS/config auto-install from USB/TFTP must be disabled",
        "check_command": "show system auto-install",
        "expected": r"(?s)(?=.*auto-install-config\s+disable)(?=.*auto-install-image\s+disable)",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system auto-install\n    set auto-install-config disable\n    set auto-install-image disable\nend",
        "reference": "FortiOS 7.0 Best Practices; NIST 800-53v5 CM-7",
    },
    {
        "id": "FG-SYS-04",
        "category": "System Global",
        "description": "Pre-login and post-login warning banners must be enabled",
        "check_command": "show system global",
        "expected": r"(?s)(?=.*pre-login-banner\s+enable)(?=.*post-login-banner\s+enable)",
        "os": "fortigate",
        "severity": "low",
        "remediation": "config system global\n    set pre-login-banner enable\n    set post-login-banner enable\nend\nconfig system replacemsg admin pre_admin-disclaimer-text\n    set buffer \"<authorized use warning>\"\nend",
        "reference": "NIST 800-53v5 AC-8; SANS Firewall Auditing Checklist",
    },
    # ─── NTP ──────────────────────────────────────────────────────────
    {
        "id": "FG-TIME-01",
        "category": "Time Synchronization",
        "description": "NTP sync must be enabled with at least two NTP servers",
        "check_command": "show system ntp",
        "expected": r"(?s)(?=.*ntpsync\s+enable)(?=.*set\s+server\s+\S+[\s\S]*?set\s+server\s+\S+)",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system ntp\n    set type custom\n    set ntpsync enable\n    config ntpserver\n        edit 1\n            set server <ntp-server-1>\n        next\n        edit 2\n            set server <ntp-server-2>\n        next\n    end\nend",
        "reference": "NIST 800-53v5 AU-8; FortiOS 7.0 Best Practices",
    },
    # ─── Password Policy ──────────────────────────────────────────────
    {
        "id": "FG-PASS-01",
        "category": "Password Policy",
        "description": "Password policy must be enabled with minimum length of 8 or more",
        "check_command": "show system password-policy",
        "expected": r"(?s)(?=.*set\s+status\s+enable)(?=.*minimum-length\s+(?:[89]|[1-9][0-9]+))",
        "os": "fortigate",
        "severity": "high",
        "remediation": "config system password-policy\n    set status enable\n    set apply-to admin-password\n    set minimum-length 14\n    set min-lower-case-letter 1\n    set min-upper-case-letter 1\n    set min-number 1\n    set min-non-alphanumeric 1\n    set expire-status enable\n    set expire-day 90\nend",
        "reference": "NIST 800-53v5 IA-5; FortiOS 7.0 Best Practices",
    },
    # ─── Logging ──────────────────────────────────────────────────────
    {
        "id": "FG-LOG-01",
        "category": "Logging",
        "description": "Local memory logging must be enabled",
        "check_command": "show log memory setting",
        "expected": r"(?s)^(?!.*set\s+status\s+disable)",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config log memory setting\n    set status enable\nend",
        "reference": "NIST 800-53v5 AU-2; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-LOG-02",
        "category": "Logging",
        "description": "Memory log severity filter must be at least 'information'",
        "check_command": "show log memory filter",
        "expected": r"(?s)(severity\s+(?:information|notification|warning|error|critical|alert|emergency)|^(?!.*severity))",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config log memory filter\n    set severity information\nend",
        "reference": "NIST 800-53v5 AU-2; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-LOG-03",
        "category": "Logging",
        "description": "Logs forwarded to FortiAnalyzer must use high encryption",
        "check_command": "show log fortianalyzer setting",
        "expected": r"(?s)enc-algorithm\s+high",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config log fortianalyzer setting\n    set enc-algorithm high\nend",
        "reference": "NIST 800-53v5 SC-8/SC-13; FortiOS 7.0 Best Practices",
    },
    # ─── Updates ──────────────────────────────────────────────────────
    {
        "id": "FG-UPD-01",
        "category": "Updates",
        "description": "AV and IPS signature databases must be present and updated (non-zero versions)",
        "check_command": "diagnose autoupdate versions",
        "expected": r"(?s)(?=.*AV\s+(?:signatures|definitions)\s*:\s*[1-9])(?=.*IPS\s+(?:signatures|definitions)\s*:\s*[1-9])",
        "os": "fortigate",
        "severity": "high",
        "remediation": "execute update-av\nexecute update-ips\ndiagnose autoupdate versions",
        "reference": "NIST 800-53v5 SI-2; FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-UPD-02",
        "category": "Updates",
        "description": "Firmware version must be reported for review against the latest official release",
        "check_command": "get system status",
        "expected": r"(?s)Version\s*:\s*(?:\S+\s+)?v?\d+\.\d+",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "Compare 'get system status' version with the latest FortiOS release from fortinet.com and upgrade during a maintenance window",
        "reference": "NIST 800-53v5 SI-2; SANS Firewall Auditing Checklist",
    },
    # ─── IPS / DoS ────────────────────────────────────────────────────
    {
        "id": "FG-IPS-01",
        "category": "IPS / DoS Protection",
        "description": "IPS anomaly mode must be set to 'enforce' or 'continuous'",
        "check_command": "show ips global",
        "expected": r"(?s)anomaly-mode\s+(?:enforce|continuous)",
        "os": "fortigate",
        "severity": "high",
        "remediation": "config ips global\n    set anomaly-mode enforce\nend",
        "reference": "FortiOS 6.4 Hardening Guide; FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-IPS-02",
        "category": "IPS / DoS Protection",
        "description": "A DoS policy with enabled anomaly detection must be configured",
        "check_command": "show firewall DoS-policy",
        "expected": r"(?s)(?=.*config\s+anomaly)(?=.*set\s+status\s+enable)",
        "os": "fortigate",
        "severity": "high",
        "remediation": "config firewall DoS-policy\n    edit 1\n        set name \"Flood\"\n        set interface \"wan1\"\n        set srcaddr all\n        set dstaddr all\n        set service ALL\n        config anomaly\n            edit \"tcp_flood\"\n                set status enable\n                set log enable\n                set action block\n                set threshold 100\n            next\n        end\n    next\nend",
        "reference": "FortiOS 6.4 Hardening Guide; NIST 800-53v5 SC-5",
    },
    # ─── Administrator Access ─────────────────────────────────────────
    {
        "id": "FG-ADM-01",
        "category": "Administrator Access",
        "description": "Maintainer backdoor account must be disabled",
        "check_command": "show system global",
        "expected": r"(?s)^(?!.*admin-maintainer\s+enable)",
        "os": "fortigate",
        "severity": "high",
        "remediation": "config system global\n    set admin-maintainer disable\nend",
        "reference": "FortiOS 6.4 Hardening Guide; NIST 800-53v5 AC-2",
    },
    {
        "id": "FG-ADM-02",
        "category": "Administrator Access",
        "description": "Telnet service must be disabled",
        "check_command": "show system global",
        "expected": r"(?s)^(?!.*set\s+telnet\s+enable)",
        "os": "fortigate",
        "severity": "critical",
        "remediation": "config system global\n    set telnet disable\nend",
        "reference": "NIST 800-53v5 CM-7; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-ADM-03",
        "category": "Administrator Access",
        "description": "SCP must be enabled for secure file transfer to/from the device",
        "check_command": "show system global",
        "expected": r"(?s)admin-scp\s+enable",
        "os": "fortigate",
        "severity": "low",
        "remediation": "config system global\n    set admin-scp enable\nend",
        "reference": "FortiOS 6.4 Hardening Guide",
    },
    {
        "id": "FG-ADM-04",
        "category": "Administrator Access",
        "description": "SSH and HTTPS management must be allowed only on the MGMT interface",
        "check_command": "show system interface",
        "expected": r'(?s)edit\s+"?mgmt"?(?:(?!next)[\s\S])*?allowaccess\s+(?=[^\n]*ssh)(?=[^\n]*https)[^\n]+',
        "os": "fortigate",
        "severity": "high",
        "remediation": "config system interface\n    edit \"MGMT\"\n        set allowaccess https ssh\n    next\nend",
        "reference": "NIST 800-53v5 AC-17; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-ADM-05",
        "category": "Administrator Access",
        "description": "Admin HTTPS and SSH ports must be changed from default 443/22",
        "check_command": "show system global",
        "expected": r"(?s)(?=.*admin-sport\s+(?!443(?:\s|$))\d+)(?=.*admin-ssh-port\s+(?!22(?:\s|$))\d+)",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system global\n    set admin-sport 7734\n    set admin-ssh-port 2345\nend",
        "reference": "NIST 800-53v5 AC-17; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-ADM-06",
        "category": "Administrator Access",
        "description": "Admin idle session timeout must be 5 minutes or less",
        "check_command": "show system global",
        "expected": r"(?s)admintimeout\s+[1-5](?:\s|$)",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system global\n    set admintimeout 5\nend",
        "reference": "NIST 800-53v5 AC-12; FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-ADM-07",
        "category": "Administrator Access",
        "description": "SSH grace time must be 30 seconds or less (or default)",
        "check_command": "show system global",
        "expected": r"(?s)(admin-ssh-grace-time\s+(?:[0-9]|[12][0-9]|30)(?:\s|$)|^(?!.*admin-ssh-grace-time))",
        "os": "fortigate",
        "severity": "low",
        "remediation": "config system global\n    set admin-ssh-grace-time 30\nend",
        "reference": "FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-ADM-08",
        "category": "Administrator Access",
        "description": "Administrator login must be restricted to a trusted host IP (trusthost)",
        "check_command": "show system admin",
        "expected": r"(?s)trusthost1\s+(?!0\.0\.0\.0\s+0\.0\.0\.0)\d+\.\d+\.\d+\.\d+\s+(?!0\.0\.0\.0)\d+\.\d+\.\d+\.\d+",
        "os": "fortigate",
        "severity": "high",
        "remediation": "config system admin\n    edit <name>\n        set trusthost1 <admin-ip>/32\n    next\nend",
        "reference": "NIST 800-53v5 AC-4/AC-17; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-ADM-09",
        "category": "Administrator Access",
        "description": "Dedicated administrator accounts must exist (not only the shared default admin)",
        "check_command": "show system admin",
        "expected": r'(?s)(?=.*edit\s+"(?!admin")[^"]+")',
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system admin\n    edit \"<admin-name>\"\n        set accprofile \"super_admin\"\n        set vdom \"root\"\n        set password <password>\n    next\nend",
        "reference": "NIST 800-53v5 AC-2/AC-6; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-ADM-10",
        "category": "Administrator Access",
        "description": "Failed login lockout threshold must be greater than 0",
        "check_command": "show system global",
        "expected": r"(?s)admin-lockout-threshold\s+(?!0(?:\s|$))\d+",
        "os": "fortigate",
        "severity": "high",
        "remediation": "config system global\n    set admin-lockout-threshold 3\nend",
        "reference": "NIST 800-53v5 AC-7; FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-ADM-11",
        "category": "Administrator Access",
        "description": "Account lockout duration must be 300 seconds or more",
        "check_command": "show system global",
        "expected": r"(?s)admin-lockout-duration\s+(?:[3-9]\d{2}|[1-9]\d{3,})",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system global\n    set admin-lockout-duration 300\nend",
        "reference": "NIST 800-53v5 AC-7; FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-ADM-12",
        "category": "Administrator Access",
        "description": "Default 'admin' account must be renamed",
        "check_command": "show system admin",
        "expected": r"(?s)^(?!.*edit\s+\"admin\")",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system admin\n    edit admin\n        rename admin to <new-name>\nend",
        "reference": "NIST 800-53v5 AC-2; SANS Firewall Auditing Checklist",
    },
    # ─── Interface Hardening ──────────────────────────────────────────
    {
        "id": "FG-IF-01",
        "category": "Interface Hardening",
        "description": "Management services (HTTP/HTTPS/SSH/Ping/SNMP) must be disabled on WAN/DMZ/LAN interfaces",
        "check_command": "show system interface",
        "expected": r"(?s)^(?!.*edit\s+\"?(?:wan|dmz|lan)[^\"\s]*\"?(?:(?!next)[\s\S])*?\bset\s+allowaccess)",
        "os": "fortigate",
        "severity": "critical",
        "remediation": "config system interface\n    edit WAN\n        unset allowaccess\n    next\n    edit DMZ\n        unset allowaccess\n    next\n    edit LAN\n        unset allowaccess\n    next\nend",
        "reference": "NIST 800-53v5 AC-17; SANS Firewall Auditing Checklist",
    },
    {
        "id": "FG-IF-02",
        "category": "Interface Hardening",
        "description": "Unused interfaces must be administratively shut down",
        "check_command": "show system interface",
        "expected": r"(?s)set\s+status\s+down",
        "os": "fortigate",
        "severity": "low",
        "remediation": "config system interface\n    edit <unused-port>\n        set status down\n    next\nend",
        "reference": "NIST 800-53v5 CM-7; FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-IF-03",
        "category": "Interface Hardening",
        "description": "ICMP redirect must be disabled on interfaces",
        "check_command": "show system interface",
        "expected": r"(?s)set\s+icmp-redirect\s+disable",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system interface\n    edit <interface>\n        set icmp-redirect disable\n    next\nend",
        "reference": "NIST 800-53v5 SC-5; FortiOS 6.4 Hardening Guide",
    },
    {
        "id": "FG-IF-04",
        "category": "Interface Hardening",
        "description": "LLDP transmission must be disabled on interfaces",
        "check_command": "show system interface",
        "expected": r"(?s)set\s+lldp-transmission\s+disable",
        "os": "fortigate",
        "severity": "low",
        "remediation": "config system interface\n    edit <interface>\n        set lldp-transmission disable\n    next\nend",
        "reference": "NIST 800-53v5 CM-7; FortiOS 6.4 Hardening Guide",
    },
    # ─── Cryptography ─────────────────────────────────────────────────
    {
        "id": "FG-CRY-01",
        "category": "Cryptography",
        "description": "Private data encryption (device private key) must be enabled",
        "check_command": "show system global",
        "expected": r"(?s)private-data-encryption\s+enable",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system global\n    set private-data-encryption enable\nend\n# Reboot required after enabling",
        "reference": "NIST 800-53v5 SC-12/SC-13; FortiOS 6.4 Hardening Guide",
    },
    {
        "id": "FG-CRY-02",
        "category": "Cryptography",
        "description": "HTTPS admin access must use TLS 1.2 or newer (TLS 1.0/1.1 excluded)",
        "check_command": "show system global",
        "expected": r'(?s)admin-https-ssl-versions\s+(?=[^\n]*tlsv1-2)(?![^\n]*tlsv1-1)[^\n]+',
        "os": "fortigate",
        "severity": "high",
        "remediation": "config system global\n    set admin-https-ssl-versions tlsv1-2\nend",
        "reference": "NIST 800-53v5 SC-8/SC-13; FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-CRY-03",
        "category": "Cryptography",
        "description": "HTTP requests must be redirected to HTTPS",
        "check_command": "show system global",
        "expected": r"(?s)admin-https-redirect\s+enable",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system global\n    set admin-https-redirect enable\nend",
        "reference": "NIST 800-53v5 SC-8; FortiOS 7.0 Best Practices",
    },
    {
        "id": "FG-CRY-04",
        "category": "Cryptography",
        "description": "Strong crypto algorithms must be enforced for FortiOS",
        "check_command": "show system global",
        "expected": r"(?s)strong-crypto\s+enable",
        "os": "fortigate",
        "severity": "high",
        "remediation": "config system global\n    set strong-crypto enable\nend",
        "reference": "NIST 800-53v5 SC-13; FortiOS 6.4 Hardening Guide",
    },
    {
        "id": "FG-CRY-05",
        "category": "Cryptography",
        "description": "Static-key SSL ciphers must be disabled",
        "check_command": "show system global",
        "expected": r"(?s)^(?!.*ssl-static-key-ciphers\s+enable)",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system global\n    set ssl-static-key-ciphers disable\nend",
        "reference": "NIST 800-53v5 SC-13; FortiOS 6.4 Hardening Guide",
    },
    {
        "id": "FG-CRY-06",
        "category": "Cryptography",
        "description": "Diffie-Hellman parameter size must be 2048 bits or larger",
        "check_command": "show system global",
        "expected": r"(?s)(dh-params\s+(?:2048|4096|8192)(?:\s|$)|^(?!.*dh-params))",
        "os": "fortigate",
        "severity": "medium",
        "remediation": "config system global\n    set dh-params 8192\nend",
        "reference": "NIST 800-53v5 SC-13; FortiOS 6.4 Hardening Guide",
    },
    # ─── SSH Hardening ────────────────────────────────────────────────
    {
        "id": "FG-SSH-01",
        "category": "SSH Hardening",
        "description": "Weak SSH algorithms (HMAC-MD5, CBC cipher) must be disabled",
        "check_command": "show system global",
        "expected": r"(?s)(?=.*ssh-hmac-md5\s+disable)(?=.*ssh-cbc-cipher\s+disable)",
        "os": "fortigate",
        "severity": "high",
        "remediation": "config system global\n    set ssh-hmac-md5 disable\n    set ssh-cbc-cipher disable\nend",
        "reference": "NIST 800-53v5 SC-13; FortiOS 6.4 Hardening Guide",
    },
]


def get_checklist(os_type: str) -> list:
    """Return the checklist for the given OS type."""
    if os_type.lower() == "linux":
        return LINUX_CHECKLIST
    elif os_type.lower() == "windows":
        return WINDOWS_CHECKLIST
    elif os_type.lower() in ("fortigate", "fortios", "fortinet"):
        return FORTIGATE_CHECKLIST
    return []


def detect_os_from_ssh_output(output: str) -> str:
    """Heuristically detect OS from SSH command output."""
    lower = output.lower()
    if any(x in lower for x in ["fortigate", "fortios", "fortinet"]):
        return "fortigate"
    if any(x in lower for x in ["ubuntu", "debian", "centos", "red hat", "linux", "fedora", "alma", "rocky"]):
        return "linux"
    if any(x in lower for x in ["windows", "microsoft", "powershell"]):
        return "windows"
    return "linux"  # default
